In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
pd.set_option("display.max_columns", 500)
pd.set_option('plotting.backend', 'plotly')
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [6]:
df_sales = pd.read_csv("data_dsmarket/item_sales.csv")
df_prices = pd.read_csv("data_dsmarket/item_prices.csv")
df_events = pd.read_csv("data_dsmarket/daily_calendar_with_events.csv")

# Tabla  Ventas

In [24]:
print(f'{df_sales.shape[0]} filas x {df_sales.shape[1]} columnas')

30490 filas x 1920 columnas

In [ ]:
df_sales.isnull().mean().head(10)

id           0.00
item         0.00
category     0.00
department   0.00
store        0.00
store_code   0.00
region       0.00
d_1          0.00
d_2          0.00
d_3          0.00
dtype: float64

In [76]:
df_sales.head()

,id,item,category,department,store,store_code,region,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,...,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,2,0,2,2,0,0,0,1,1,0,2,0,1,1,2,0,1,0,0,0,2,1,0,1,1,2,0,0,0,0,0,0,0,1,0,1,0,1,0,3,1,1,0,1,1,2,0,0,0,0,1,1,0,0,0,0,3,0,1,0,0,0,0,1,1,1,0,1,0,2,0,0,0,0,2,0,0,0,0,1,1,2,0,0,0,0,2,0,0,1,1,1,1,0,0,0,0,0,1,2,2,0,1,0,0,0,0,1,2,1,0,0,0,0,0,1,0,3,0,1,2,1,0,3,0,0,0,1,0,2,2,1,0,0,1,2,0,1,0,1,4,0,0,5,0,0,0,0,0,0,2,1,2,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0,0,0,2,2,0,0,1,4,0,0,0,0,1,1,2,0,4,0,1,0,1,4,2,0,2,0,1,1,0,1,0,0,1,1,3,0,0,0,1,1,1,3,1,3,1,2,2,0,1,1,1,1,0,0,0,0,0,1,0,4,2,3,0,1,2,0,0,0,1,1,3,0,1,1,1,3,0,1,1
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1,1,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,...,1,0,0,1,1,0,0,0,3,4,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,2,1,0,0,1,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,1,0,2,1,0,0,0,1,1,0,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0,1,0,1,1,0,3,0,0,0,0,0,0,0,1,0,0,0,0,0,2,1,0,0,1,1,0,2,0,1,0,2,1,1,5,0,1,0,3,5,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,2,1,0,3,0,1,2,0,3,1,0,0,1,0,1,0,0,0,0,2,0,1,0,1,0,1,1,0,1,0,1,0,0,0,1,2,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,2,0,1,0,0,2,0,0,0,1,0,0,1,0,0,2,0,0,0,0,0,0,0,0,2,0,2,3,0,1,3,1,2,2,3,0,1,1,0,0,0,0,2,3,1,1,4,3,2,1,2,2,0,1,5,2,0,1,2,3,0,1,2,1,3,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,6,1,1,2,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,2,2,1,2,1,1,1,0,1,1,1
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,2,0,1,0,0,0,0,0,0,2,0,1,0,0,1,1,1,0,2,3,1,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,1,2,3,0,2,0,0,2,2,0,0,2,1,2,1,1,1,2,0,0,1,0,1,3,1,0,0,0,0,3,5,2,2,1,1,1,1,1,1,0,0,2,1,1,1,2,0,0,0,2,5,6,0,0,0,0,0,0,0,0,0,0,0,2,1,2,0,1,0,2,0,0,5,1,0,0,1,3,1,3,5,1,3,0,3,4,4,0,0,1,3,1,4,0,0,2,0,2,0,1,4,2,1,0,2,1,3,6,1,1,2,1,2,3,1,2,0,0,0,3,4,5,1,0,0,1,0,1,4,6,3,1,1,0,1,4,5,1,1,4,0,0,0,1,2,2,1,1,6,2,4,4,0,0,0,2,2,0,1,1,3,1,2,4,2,1,3,...,0,0,0,11,2,2,1,1,2,1,1,2,1,1,0,3,0,2,14,0,0,0,3,3,1,1,1,1,0,3,3,1,7,3,1,0,0,1,0,1,1,0,0,2,1,4,4,3,0,2,0,0,1,3,3,0,2,1,2,4,7,0,2,1,0,5,5,2,2,4,1,0,0,3,1,0,0,0,3,1,3,3,0,0,4,1,1,1,1,3,3,1,0,3,0,1,3,3,3,2,2,2,4,3,0,5,1,3,3,2,0,0,1,1,0,2,2,2,3,2,1,2,0,5,0,1,0,0,0,3,4,0,0,1,5,3,2,2,0,1,1,0,2,1,0,2,4,0,0,0,3,2,4,3,1,2,3,0,8,2,1,2,2,5,2,6,1,0,3,5,1,1,6,4,3,2,2,3,2,1,0,0,0,2,0,5,4,2,1,1,2,3,0,6,0,0,0,1,0,1,5,3,1,0,0,0,1,2,3,0,1,3,4,2,1,4,1,3,5,0,6,6,0,0,0,0,3,1,2,1,3,1,0,2,5,4,2,0,3,0,1,0,5,4,1,0,1,3,7,2
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,6,0,3,2,3,5,3,1,0,0,1,0,2,2,4,0,0,3,1,1,1,2,2,0,0,0,0,0,0,3,7,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,2,0,0,0,0,0,0,0,2,0,6,2,4,2,0,0,3,2,4,1,0,0,0,0,1,1,1,2,0,0,0,0,0,0,0,0,2,6,7,9,4,7,6,3,4,2,0,1,5,2,2,0,0,0,0,0,0,1,...,2,0,5,2,0,0,1,0,3,1,0,1,0,2,1,0,0,1,3,1,1,0,4,0,2,1,2,4,0,1,0,0,3,1,2,2,0,1,1,0,4,0,0,4,0,2,2,2,1,2,1,1,1,4,0,2,1,2,0,0,1,0,1,1,2,2,3,1,0,2,3,0,1,1,4,0,3,2,1,2,1,2,2,1,2,0,1,1,2,0,2,0,0,0,4,2,1,2,0,0,0,0,0,2,1,0,0,1,2,0,1,2,1,2,1,2,3,3,0,3,1,5,3,2,1,2,3,4,0,0,1,0,0,1,0,0,1,0,0,0,0,2,0,0,3,0,0,1,2,2,0,1,0,0,0,1,0,0,3,0,0,1,1,0,3,1,0,4,1,2,0,0,0,1,1,2,0,0,5,2,2,2,1,0,0,0,3,0,0,0,3,1,1,1,1,2,1,0,0,1,0,2,1,1,0,3,1,1,2,1,1,0,3,2,2,2,3,1,0,0,0,0,1,0,4,4,0,1,4,0,1,0,1,0,1,1,2,0,1,1,2,1,1,0,1,1,2,2,2,4

In [18]:
df_sales.dtypes.head(10)

id            object
item          object
category      object
department    object
store         object
store_code    object
region        object
d_1            int64
d_2            int64
d_3            int64
dtype: object

In [36]:
for col in ['id', 'item', 'category', 'department', 'store', 'store_code', 'region']:
    print(f'\n{col} -> {df_sales[col].nunique()} valores únicos')

id -> 30490 valores únicos

item -> 3049 valores únicos

category -> 3 valores únicos

department -> 7 valores únicos

store -> 10 valores únicos

store_code -> 10 valores únicos

region -> 3 valores únicos

In [ ]:
df_sales['id'].value_counts().sum()

np.int64(30490)

In [89]:
df_sales['item'].value_counts().sort_index()

item
ACCESORIES_1_001     10
ACCESORIES_1_002     10
ACCESORIES_1_003     10
ACCESORIES_1_004     10
ACCESORIES_1_005     10
                     ..
SUPERMARKET_3_823    10
SUPERMARKET_3_824    10
SUPERMARKET_3_825    10
SUPERMARKET_3_826    10
SUPERMARKET_3_827    10
Name: count, Length: 3049, dtype: int64

In [37]:
df_sales['category'].value_counts()

category
SUPERMARKET      14370
HOME_&_GARDEN    10470
ACCESORIES        5650
Name: count, dtype: int64

In [ ]:
df_sales['department'].value_counts().sort_index()

department
ACCESORIES_1       4160
ACCESORIES_2       1490
HOME_&_GARDEN_1    5320
HOME_&_GARDEN_2    5150
SUPERMARKET_1      2160
SUPERMARKET_2      3980
SUPERMARKET_3      8230
Name: count, dtype: int64

In [39]:
df_sales['store'].value_counts()

store
Greenwich_Village    3049
Harlem               3049
Tribeca              3049
Brooklyn             3049
South_End            3049
Roxbury              3049
Back_Bay             3049
Midtown_Village      3049
Yorktown             3049
Queen_Village        3049
Name: count, dtype: int64

In [83]:
df_sales['store_code'].value_counts().sort_index()

store_code
BOS_1    3049
BOS_2    3049
BOS_3    3049
NYC_1    3049
NYC_2    3049
NYC_3    3049
NYC_4    3049
PHI_1    3049
PHI_2    3049
PHI_3    3049
Name: count, dtype: int64

In [85]:
df_sales['region'].value_counts()

region
New York        12196
Boston           9147
Philadelphia     9147
Name: count, dtype: int64

# Tabla  Precios

In [54]:
print(f'{df_prices.shape[0]:,} filas x {df_prices.shape[1]:,} columnas')

6,965,706 filas x 5 columnas

In [ ]:
df_prices.isnull().mean()

item         0.00
category     0.00
store_code   0.00
yearweek     0.04
sell_price   0.00
dtype: float64

In [12]:
df_prices.head()

               item    category store_code  yearweek  sell_price
0  ACCESORIES_1_001  ACCESORIES      NYC_1 201328.00       12.74
1  ACCESORIES_1_001  ACCESORIES      NYC_1 201329.00       12.74
2  ACCESORIES_1_001  ACCESORIES      NYC_1 201330.00       10.99
3  ACCESORIES_1_001  ACCESORIES      NYC_1 201331.00       10.99
4  ACCESORIES_1_001  ACCESORIES      NYC_1 201332.00       10.99

In [43]:
df_prices.dtypes

item           object
category       object
store_code     object
yearweek      float64
sell_price    float64
dtype: object

## Categóricas

In [44]:
df_prices['item'].value_counts()

item
SUPERMARKET_3_587      2870
HOME_&_GARDEN_1_177    2870
HOME_&_GARDEN_2_283    2870
ACCESORIES_1_337       2870
SUPERMARKET_1_032      2870
                       ...
HOME_&_GARDEN_1_308     652
HOME_&_GARDEN_1_159     633
HOME_&_GARDEN_1_242     610
SUPERMARKET_3_296       602
SUPERMARKET_2_379       543
Name: count, Length: 3049, dtype: int64

In [45]:
df_prices['category'].value_counts()

category
SUPERMARKET      3239821
HOME_&_GARDEN    2418627
ACCESORIES       1307258
Name: count, dtype: int64

In [90]:
df_prices['store_code'].value_counts().sort_index()

store_code
BOS_1    712527
BOS_2    713960
BOS_3    703682
NYC_1    711073
NYC_2    649002
NYC_3    706585
NYC_4    691375
PHI_1    678209
PHI_2    690546
PHI_3    708747
Name: count, dtype: int64

## Numéricas

In [91]:
df_prices['yearweek'].value_counts().sort_index()

yearweek
201105.00    10932
201106.00    11975
201107.00    12519
201108.00    12799
201109.00    13033
             ...
201613.00    30490
201614.00    30490
201615.00    30490
201616.00    30490
201617.00    30490
Name: count, Length: 279, dtype: int64

In [94]:
df_prices['sell_price'].value_counts().sort_index()

sell_price
0.01       3
0.01       5
0.01       5
0.02       2
0.06      89
          ..
56.65      1
60.98      1
65.77      1
76.83     14
134.15     3
Name: count, Length: 1892, dtype: int64

# Tabla  Eventos

In [55]:
print(f'{df_events.shape[0]:,} filas x {df_events.shape[1]:,} columnas')

1,913 filas x 5 columnas

In [ ]:
df_events.isnull().mean()

date          0.00
weekday       0.00
weekday_int   0.00
d             0.00
event         0.99
dtype: float64

In [13]:
df_events.head()

         date    weekday  weekday_int    d event
0  2011-01-29   Saturday            1  d_1   NaN
1  2011-01-30     Sunday            2  d_2   NaN
2  2011-01-31     Monday            3  d_3   NaN
3  2011-02-01    Tuesday            4  d_4   NaN
4  2011-02-02  Wednesday            5  d_5   NaN

In [58]:
df_events.dtypes

date           object
weekday        object
weekday_int     int64
d              object
event          object
dtype: object

In [114]:
df_events['event'].value_counts(dropna=False)

event
NaN               1887
SuperBowl            6
Ramadan starts       5
Thanksgiving         5
NewYear              5
Easter               5
Name: count, dtype: int64

In [97]:
df_events['date'].value_counts().sort_index()

date
2011-01-29    1
2011-01-30    1
2011-01-31    1
2011-02-01    1
2011-02-02    1
             ..
2016-04-20    1
2016-04-21    1
2016-04-22    1
2016-04-23    1
2016-04-24    1
Name: count, Length: 1913, dtype: int64

In [98]:
df_events['weekday'].value_counts()

weekday
Saturday     274
Sunday       274
Monday       273
Tuesday      273
Wednesday    273
Thursday     273
Friday       273
Name: count, dtype: int64

In [99]:
df_events['weekday_int'].value_counts()

weekday_int
1    274
2    274
3    273
4    273
5    273
6    273
7    273
Name: count, dtype: int64

In [105]:
df_events['d'].value_counts()

d
d_1       1
d_1272    1
d_1284    1
d_1283    1
d_1282    1
         ..
d_635     1
d_634     1
d_633     1
d_632     1
d_1913    1
Name: count, Length: 1913, dtype: int64

In [75]:
df_events['d'].head(10)

0     d_1
1     d_2
2     d_3
3     d_4
4     d_5
5     d_6
6     d_7
7     d_8
8     d_9
9    d_10
Name: d, dtype: object

In [103]:
df_events['d'].tail(10)

1903    d_1904
1904    d_1905
1905    d_1906
1906    d_1907
1907    d_1908
1908    d_1909
1909    d_1910
1910    d_1911
1911    d_1912
1912    d_1913
Name: d, dtype: object